export type AiMessageRole = 'system' | 'user' | 'assistant' | 'tool';

export interface AiToolFunctionCall {
  name: string;
  arguments: string;
}

export interface AiToolCall {
  id: string;
  type: 'function';
  function: AiToolFunctionCall;
}

export interface AiToolDefinition {
  type: 'function';
  function: {
    name: string;
    description: string;
    parameters: Record<string, unknown>;
  };
}

export interface AiToolMessage {
  role: 'tool';
  tool_call_id: string;
  content: string;
}

export interface AiCompletionMessagePayload {
  role: AiMessageRole;
  content: string;
  tool_calls?: AiToolCall[];
  tool_call_id?: string;
}

export interface AiChatAttachment {
  name: string;
  type?: string;
  rows?: number;
  columns?: number;
}

export interface AiWorksheetOption {
  index: number;
  name: string;
  rows: number;
  columns: number;
}

export interface AiChatMessage {
  id: string;
  role: AiMessageRole;
  content: string;
  createdAt: number;
  autoGenerated?: boolean;
  hidden?: boolean;
  agentModeRequest?: boolean;
  tokenCount?: number;
  responseTimeMs?: number;
  parentUserId?: string;
  attachment?: AiChatAttachment;
  worksheetOptions?: AiWorksheetOption[];
  reasoning?: string;
  toolCalls?: AiToolCall[];
  toolCallId?: string;
  hiddenFromTranscript?: boolean;
}
