export type AiMessageRole = 'user' | 'assistant';

export interface AiChatMessage {
  id: string;
  role: AiMessageRole;
  content: string;
  createdAt: number;
  autoGenerated?: boolean;
  tokenCount?: number;
  responseTimeMs?: number;
  parentUserId?: string;
}
