export type AiMessageRole = 'user' | 'assistant';

export interface AiChatAttachment {
  name: string;
  type?: string;
  rows?: number;
  columns?: number;
}

export interface AiWorksheetOption {
  index: number;
  name: string;
  rows: number;
  columns: number;
}

export interface AiChatMessage {
  id: string;
  role: AiMessageRole;
  content: string;
  createdAt: number;
  autoGenerated?: boolean;
  tokenCount?: number;
  responseTimeMs?: number;
  parentUserId?: string;
  attachment?: AiChatAttachment;
  worksheetOptions?: AiWorksheetOption[];
}
