{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spc.fullname" . }}-config
  labels:
    {{- include "spc.labels" . | nindent 4 }}
data:
  runtime-config.js: |
{{ include "spc.runtimeConfigJs" . | indent 4 }}
  {{- range $k, $v := .Values.config.data }}
  {{- if ne $k "runtime-config.js" }}
  {{ $k }}: |
{{ tpl $v $ | indent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
