{{- if and .Values.gateway.enabled .Values.gateway.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "spc.gatewaySecretName" . }}
  labels:
    {{- include "spc.gatewayLabels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.gateway.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.gateway.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.gateway.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "spc.gatewaySecretName" . }}
  data:
    {{- toYaml .Values.gateway.externalSecret.data | nindent 4 }}
{{- end }}