{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "spc.fullname" . }}
  labels:
    {{- include "spc.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "spc.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {} # allow all ingress within namespace (adjust if needed)
  egress:
    {{- if .Values.networkPolicy.allowDNS }}
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
    {{- range .Values.networkPolicy.allowedEgressCIDRs }}
    - to:
        - ipBlock:
            cidr: {{ . }}
    {{- end }}
{{- end }}
