apiVersion: v1
kind: Service
metadata:
  name: {{ include "spc.fullname" . }}
  labels:
    {{- include "spc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.nginxExporter.enabled }}
    - port: {{ .Values.nginxExporter.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "spc.selectorLabels" . | nindent 4 }}
