import React, { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Loader2, Send, Sparkles, X, RefreshCcw, Hash, Clock, Copy, Download, Edit3, Check, FileSpreadsheet } from 'lucide-react';
import { useAppContext } from '../../context/AppContext';
import { useLanguage } from '../../context/LanguageContext';
import {
  buildAgentAutopilotPrompt,
  buildAssistantSystemPrompt,
  buildDatasetUpdatePrompt,
  buildInitialUserPrompt,
  summarizeDatasetForAi,
} from '../../utils/aiHelpers';
import type { AiChatAttachment, AiChatMessage, AiWorksheetOption } from '../../types/AiTypes';
import { chartMeta } from '../../types/chartMeta';
import { MarkdownText } from '../common/MarkdownText';
import {
  ChainOfThought,
  ChainOfThoughtHeader,
  ChainOfThoughtContent,
  ChainOfThoughtStep,
} from '../ai-elements/chain-of-thought';
import {
  AGENT_CHART_TYPES,
  buildAgentTurnRequest,
  type AgentControlPatch,
  type AgentControlsSnapshotInput,
  type AgentTurnResponse,
} from '../../utils/aiTools';
import { resolveAiRuntimeConfig } from '../../utils/runtimeConfig';

interface AiAssistantPanelProps {
  onClose: () => void;
}

const hasOwn = <T extends object>(value: T, key: PropertyKey): boolean => (
  Object.prototype.hasOwnProperty.call(value, key)
);

const AiAssistantPanel: React.FC<AiAssistantPanelProps> = ({ onClose }) => {
  const {
    rawData,
    processedData,
    selectedColumns,
    xAxisColumn,
    denominatorColumn,
    sampleSize,
    selectedChartType,
    chartOptions,
    setSelectedChartType,
    setChartOptions,
    setSelectedColumns,
    setXAxisColumn,
    setDenominatorColumn,
    setSampleSize,
    setActiveSheetIndex,
  } = useAppContext();
  
  const { language, t } = useLanguage();

  const [messages, setMessages] = useState<AiChatMessage[]>([]);
  const [inputValue, setInputValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [hasInitialized, setHasInitialized] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editDraft, setEditDraft] = useState('');
  const [agentModeEnabled, setAgentModeEnabled] = useState(false);
  const [agentFeedback, setAgentFeedback] = useState<string | null>(null);
  const [selectedAiSheetIndex, setSelectedAiSheetIndex] = useState<number | null>(null);
  const conversationRef = useRef<AiChatMessage[]>([]);
  const lastSummaryRef = useRef<string | null>(null);
  const scrollContainerRef = useRef<HTMLDivElement | null>(null);
  const sheetSelectionContextRef = useRef<string | null>(null);
  const agentAutopilotContextRef = useRef<string | null>(null);
  const suppressNextAgentAutopilotRef = useRef(false);
  const requestInFlightRef = useRef(false);

  const worksheetOptions = useMemo<AiWorksheetOption[]>(() => {
    if (!rawData?.sheets?.length) {
      return [];
    }

    return rawData.sheets.map((sheet, index) => ({
      index,
      name: sheet.name,
      rows: sheet.data.length,
      columns: sheet.headers.length,
    }));
  }, [rawData]);

  const requiresWorksheetSelection = Boolean(rawData?.sheets && rawData.sheets.length > 1 && selectedAiSheetIndex === null);

  const systemPrompt = useMemo(() => buildAssistantSystemPrompt(language, agentModeEnabled), [agentModeEnabled, language]);
  const friendlyChartName = useMemo(
    () => chartMeta[selectedChartType]?.name ?? selectedChartType,
    [selectedChartType],
  );
  const datasetSummary = useMemo(
    () =>
      summarizeDatasetForAi(
        rawData,
        processedData,
        selectedColumns,
        xAxisColumn,
        denominatorColumn,
        sampleSize,
      ),
    [denominatorColumn, processedData, rawData, sampleSize, selectedColumns, xAxisColumn],
  );

  const appendAssistantMessage = useCallback((content: string) => {
    const assistantMessage: AiChatMessage = {
      id: `assistant-${Date.now()}`,
      role: 'assistant',
      content,
      createdAt: Date.now(),
      autoGenerated: true,
    };
    const updated = [...conversationRef.current, assistantMessage];
    conversationRef.current = updated;
    setMessages(updated);
    return assistantMessage;
  }, []);

  const tokenCountFor = (content: string) => {
    const wordCount = content.trim() ? content.trim().split(/\s+/).length : 0;
    return Math.max(1, Math.ceil(wordCount * 1.35));
  };

  const applyAgentControlPatch = useCallback((patch: AgentControlPatch | null | undefined) => {
    if (!patch) {
      return;
    }

    const headers = rawData?.headers ?? [];
    const applied: string[] = [];
    let nextChartType = selectedChartType;
    let nextSelectedColumns = selectedColumns;

    if (typeof patch.chartType === 'string' && AGENT_CHART_TYPES.includes(patch.chartType)) {
      nextChartType = patch.chartType;
      setSelectedChartType(patch.chartType);
      applied.push(t('ai.agentProposedChart'));
    }

    if (Array.isArray(patch.yColumns)) {
      const nextYColumns = Array.from(new Set(patch.yColumns.filter((value): value is string => typeof value === 'string')))
        .filter((value) => headers.includes(value));
      if (nextYColumns.length > 0 || patch.yColumns.length === 0) {
        nextSelectedColumns = nextYColumns;
        setSelectedColumns(nextYColumns);
        applied.push(t('ai.agentProposedY'));
      }
    }

    if (hasOwn(patch, 'xAxisColumn')) {
      if (patch.xAxisColumn === null || patch.xAxisColumn === undefined) {
        setXAxisColumn(null);
        applied.push(t('ai.agentProposedX'));
      } else if (typeof patch.xAxisColumn === 'string' && headers.includes(patch.xAxisColumn)) {
        setXAxisColumn(patch.xAxisColumn);
        applied.push(t('ai.agentProposedX'));
      }
    }

    if (hasOwn(patch, 'denominatorColumn')) {
      if (patch.denominatorColumn === null || patch.denominatorColumn === undefined) {
        setDenominatorColumn(null);
        applied.push('denominatorColumn');
      } else if (typeof patch.denominatorColumn === 'string' && headers.includes(patch.denominatorColumn)) {
        setDenominatorColumn(patch.denominatorColumn);
        applied.push('denominatorColumn');
      }
    }

    const shouldUseYColumnsAsSubgroups =
      (nextChartType === 'xBarS' || nextChartType === 'xBarR') && nextSelectedColumns.length > 1;
    const nextSampleSize = shouldUseYColumnsAsSubgroups
      ? nextSelectedColumns.length
      : patch.sampleSize;
    if (typeof nextSampleSize === 'number' && Number.isFinite(nextSampleSize)) {
      setSampleSize(Math.max(2, Math.min(25, Math.round(nextSampleSize))));
      applied.push(t('ai.agentProposedSample'));
    }

    const nextChartOptions = { ...chartOptions };
    let chartOptionsChanged = false;
    const assignChartOption = <K extends keyof typeof nextChartOptions>(key: K, value: typeof nextChartOptions[K] | undefined, label: string) => {
      if (value === undefined || value === nextChartOptions[key]) {
        return;
      }
      nextChartOptions[key] = value;
      chartOptionsChanged = true;
      applied.push(label);
    };

    assignChartOption('title', typeof patch.chartLabel === 'string' ? patch.chartLabel : undefined, t('controlPanel.chartTitle'));
    assignChartOption('xAxisLabel', typeof patch.zAxisLabel === 'string' ? patch.zAxisLabel : undefined, t('controlPanel.xAxisLabel'));
    assignChartOption('yAxisLabel', typeof patch.yAxisLabel === 'string' ? patch.yAxisLabel : undefined, t('controlPanel.yAxisLabel'));
    assignChartOption('showControlLimits', typeof patch.showControlLimits === 'boolean' ? patch.showControlLimits : undefined, 'showControlLimits');
    assignChartOption('showCenterLine', typeof patch.showCenterLine === 'boolean' ? patch.showCenterLine : undefined, 'showCenterLine');
    assignChartOption('showRuleViolations', typeof patch.showRuleViolations === 'boolean' ? patch.showRuleViolations : undefined, 'showRuleViolations');
    assignChartOption('showSigma1', typeof patch.showSigma1 === 'boolean' ? patch.showSigma1 : undefined, 'showSigma1');
    assignChartOption('showSigma2', typeof patch.showSigma2 === 'boolean' ? patch.showSigma2 : undefined, 'showSigma2');
    assignChartOption('showSigma3', typeof patch.showSigma3 === 'boolean' ? patch.showSigma3 : undefined, 'showSigma3');
    assignChartOption('colorScheme', typeof patch.colorScheme === 'string' ? patch.colorScheme : undefined, 'colorScheme');

    if (chartOptionsChanged) {
      setChartOptions(nextChartOptions);
    }

    setAgentFeedback(
      applied.length
        ? `${t('ai.agentApplied')} ${applied.join(', ')}`
        : t('ai.agentNoChangeDetected'),
    );

    if (applied.length > 0) {
      suppressNextAgentAutopilotRef.current = true;
    }
  }, [chartOptions, rawData?.headers, selectedChartType, selectedColumns, setChartOptions, setDenominatorColumn, setSampleSize, setSelectedChartType, setSelectedColumns, setXAxisColumn, t]);

  const runAgentModeTurn = useCallback(async (
    conversationForRequest: AiChatMessage[],
    endpoint: string,
    apiKey: string,
    model: string,
    shouldSendTemperature: boolean,
  ): Promise<AgentTurnResponse> => {
    const agentState: AgentControlsSnapshotInput = {
      rawData,
      selectedChartType,
      chartOptions,
      selectedColumns,
      xAxisColumn,
      denominatorColumn,
      sampleSize,
      language,
      agentModeEnabled: true,
      selectedAiSheetIndex,
    };

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify(buildAgentTurnRequest(agentState, conversationForRequest, {
        model,
        systemPrompt,
        datasetSummary,
        processedData,
        ...(shouldSendTemperature ? { temperature: 0.2 } : {}),
      })),
    });

    if (!response.ok) {
      throw new Error(await extractAiErrorMessage(response));
    }

    return await response.json() as AgentTurnResponse;
  }, [chartOptions, datasetSummary, denominatorColumn, language, processedData, rawData, sampleSize, selectedAiSheetIndex, selectedChartType, selectedColumns, systemPrompt, xAxisColumn]);

  const extractAiErrorMessage = async (response: Response): Promise<string> => {
    const fallback = `AI service request failed (${response.status}${response.statusText ? ` ${response.statusText}` : ''}).`;

    try {
      const contentType = response.headers.get('content-type') || '';
      if (contentType.includes('application/json')) {
        const payload = await response.json();
        const message =
          payload?.error?.message
          ?? payload?.error
          ?? payload?.detail
          ?? payload?.message;
        if (typeof message === 'string' && message.trim()) {
          return message.trim();
        }
      } else {
        const bodyText = (await response.text()).trim();
        if (bodyText) {
          return bodyText;
        }
      }
    } catch {
      // ignore parse errors and use fallback
    }

    return fallback;
  };

  const handleCopy = async (content: string) => {
    try {
      await navigator.clipboard.writeText(content);
    } catch {
      // noop
    }
  };

  const handleDownload = (content: string) => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'assistant-response.txt';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const appendWorksheetSelectionMessage = useCallback(() => {
    if (!rawData?.sheets || rawData.sheets.length <= 1) {
      return;
    }

    const lastMessage = conversationRef.current[conversationRef.current.length - 1];
    if (lastMessage?.role === 'assistant' && lastMessage.worksheetOptions?.length) {
      return;
    }

    const sheetMessage: AiChatMessage = {
      id: `assistant-sheets-${Date.now()}`,
      role: 'assistant',
      content: t('ai.selectWorksheetPrompt'),
      createdAt: Date.now(),
      autoGenerated: true,
      worksheetOptions,
    };

    const updated = [...conversationRef.current, sheetMessage];
    conversationRef.current = updated;
    setMessages(updated);
  }, [rawData?.sheets, t, worksheetOptions]);

  const handleWorksheetSelect = useCallback((sheetIndex: number) => {
    if (!rawData?.sheets || sheetIndex < 0 || sheetIndex >= rawData.sheets.length) {
      return;
    }

    setActiveSheetIndex(sheetIndex);
    setSelectedAiSheetIndex(sheetIndex);
    setAgentFeedback(null);
    appendAssistantMessage(
      `${t('ai.worksheetSelectedPrefix')}: ${rawData.sheets[sheetIndex].name}`,
    );
  }, [appendAssistantMessage, rawData?.sheets, setActiveSheetIndex, t]);

  const sendMessage = useCallback(
    async (
      content: string,
      options?: {
        skipInputReset?: boolean;
        autoGenerated?: boolean;
        attachment?: AiChatAttachment;
        hideUserMessage?: boolean;
      },
    ) => {
      if (requiresWorksheetSelection) {
        setError(null);
        appendWorksheetSelectionMessage();
        return;
      }

      const trimmed = content.trim();
      if (!trimmed) {
        return;
      }

      if (requestInFlightRef.current) {
        return;
      }

      requestInFlightRef.current = true;
      const requestAgentMode = agentModeEnabled;

      const userMessage: AiChatMessage = {
        id: `user-${Date.now()}`,
        role: 'user',
        content: trimmed,
        createdAt: Date.now(),
        autoGenerated: options?.autoGenerated,
        hidden: options?.hideUserMessage,
        agentModeRequest: requestAgentMode,
        attachment: options?.attachment,
      };

      const conversationForRequest = [...conversationRef.current, userMessage];
      const conversationWithUser = options?.hideUserMessage
        ? conversationRef.current
        : conversationForRequest;
      conversationRef.current = conversationWithUser;
      setMessages(conversationWithUser);
      if (!options?.skipInputReset) {
        setInputValue('');
      }

      setIsLoading(true);
      setError(null);

      const { apiUrl, apiKey, model } = resolveAiRuntimeConfig();

      if (!apiUrl || !apiKey || !model) {
        setError(t('ai.notConfigured'));
        appendAssistantMessage(
          t('ai.configError'),
        );
        setIsLoading(false);
        requestInFlightRef.current = false;
        return;
      }

      const trimmedUrl = apiUrl.replace(/\/$/, '');
      const endpoint = /\/v1\/chat\/completions$/i.test(trimmedUrl)
        ? trimmedUrl
        : `${trimmedUrl}/v1/chat/completions`;
      const agentEndpoint = /\/v1\/chat\/completions$/i.test(trimmedUrl)
        ? trimmedUrl.replace(/\/v1\/chat\/completions$/i, '/v1/agent/turn')
        : `${trimmedUrl}/v1/agent/turn`;
      const normalizedModel = model.trim().toLowerCase();
      const shouldSendTemperature = !normalizedModel.startsWith('gpt');

      try {
        const startTime = Date.now();
        if (requestAgentMode) {
          const result = await runAgentModeTurn(conversationForRequest, agentEndpoint, apiKey, model, shouldSendTemperature);
          applyAgentControlPatch(result.controlPatch);
          const assistantMessage: AiChatMessage = {
            id: `assistant-${Date.now()}`,
            role: 'assistant',
            content: result.content,
            createdAt: Date.now(),
            tokenCount: tokenCountFor(result.content),
            responseTimeMs: Math.max(0, Date.now() - startTime),
            parentUserId: userMessage.id,
            ...(result.reasoning ? { reasoning: result.reasoning } : {}),
            agentModeRequest: true,
          };
          const conversationWithAssistant = [...conversationWithUser, assistantMessage];
          conversationRef.current = conversationWithAssistant;
          setMessages(conversationWithAssistant);
          return;
        }

        const response = await fetch(endpoint, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${apiKey}`,
          },
          body: JSON.stringify({
            model,
            messages: [
              { role: 'system', content: systemPrompt },
              ...conversationForRequest.map((message) => ({
                role: message.role,
                content: message.content,
              })),
            ],
            ...(shouldSendTemperature ? { temperature: 0.2 } : {}),
            stream: true,
          }),
        });

        // If the server does not support streaming, fall back to JSON body
        const contentType = response.headers.get('content-type') || '';
        const supportsStream = response.ok && contentType.includes('text/event-stream');

        if (supportsStream && response.body) {
          const assistantMessage: AiChatMessage = {
            id: `assistant-${Date.now()}`,
            role: 'assistant',
            content: '',
            createdAt: Date.now(),
            parentUserId: userMessage.id,
            agentModeRequest: requestAgentMode,
          };
          const withAssistant = [...conversationWithUser, assistantMessage];
          conversationRef.current = withAssistant;
          setMessages(withAssistant);

          const reader = response.body.getReader();
          const decoder = new TextDecoder('utf-8');
          let buffer = '';
          let doneStreaming = false;

          const applyDelta = (delta: string) => {
            if (!delta) return;
            assistantMessage.content += delta;
            // Trigger React update with the mutated message
            setMessages([...conversationRef.current]);
          };

          const applyReasoningDelta = (delta: string) => {
            if (!delta) return;
            assistantMessage.reasoning = (assistantMessage.reasoning ?? '') + delta;
            setMessages([...conversationRef.current]);
          };

          const processEvent = (rawEvent: string) => {
            const lines = rawEvent.split('\n');
            for (const line of lines) {
              const trimmed = line.trim();
              if (!trimmed || trimmed.startsWith(':')) continue; // comment/keep-alive
              if (!trimmed.startsWith('data:')) continue;
              const data = trimmed.slice(5).trim();
              if (data === '[DONE]') {
                doneStreaming = true;
                return;
              }
              try {
                const parsed = JSON.parse(data);
                // OpenAI Chat Completions delta shape
                const piece: string | undefined = parsed?.choices?.[0]?.delta?.content;
                if (typeof piece === 'string') {
                  applyDelta(piece);
                }
                // vLLM reasoning_content (Gemma 4 thinking mode, DeepSeek R1, etc.)
                const reasoningPiece: string | undefined = parsed?.choices?.[0]?.delta?.reasoning_content;
                if (typeof reasoningPiece === 'string') {
                  applyReasoningDelta(reasoningPiece);
                }
              } catch {
                // Non-JSON data line; ignore
              }
            }
          };

          // Read the stream
          while (!doneStreaming) {
            const { done, value } = await reader.read();
            if (done) break;
            buffer += decoder.decode(value, { stream: true });
            let boundary = buffer.indexOf('\n\n');
            while (boundary !== -1) {
              const eventChunk = buffer.slice(0, boundary);
              buffer = buffer.slice(boundary + 2);
              processEvent(eventChunk);
              if (doneStreaming) break;
              boundary = buffer.indexOf('\n\n');
            }
          }

          // If any remainder exists, attempt to process it
          if (buffer && !doneStreaming) {
            processEvent(buffer);
          }

          // Finalize conversation state
          assistantMessage.tokenCount = tokenCountFor(assistantMessage.content);
          assistantMessage.responseTimeMs = Math.max(0, Date.now() - startTime);
          conversationRef.current = [...conversationRef.current];
          setMessages([...conversationRef.current]);
        } else {
          if (!response.ok) {
            throw new Error(await extractAiErrorMessage(response));
          }
          const payload = await response.json();
          const assistantText: string | undefined = payload?.choices?.[0]?.message?.content?.trim();
          if (!assistantText) {
            throw new Error('The AI service returned an empty response.');
          }
          const reasoningText: string | undefined = payload?.choices?.[0]?.message?.reasoning_content?.trim();
          const assistantMessage: AiChatMessage = {
            id: `assistant-${Date.now()}`,
            role: 'assistant',
            content: assistantText,
            createdAt: Date.now(),
            tokenCount: tokenCountFor(assistantText),
            responseTimeMs: 0,
            parentUserId: userMessage.id,
            ...(reasoningText ? { reasoning: reasoningText } : {}),
            agentModeRequest: requestAgentMode,
          };
          assistantMessage.responseTimeMs = Math.max(0, Date.now() - startTime);
          const conversationWithAssistant = [...conversationWithUser, assistantMessage];
          conversationRef.current = conversationWithAssistant;
          setMessages(conversationWithAssistant);
        }
      } catch (err) {
        const message = err instanceof Error ? err.message : 'Unexpected error while contacting the AI service.';
        setError(message);
        appendAssistantMessage(`${t('ai.serviceError')}${message}`);
      } finally {
        setIsLoading(false);
        requestInFlightRef.current = false;
      }
    },
    [agentModeEnabled, appendAssistantMessage, appendWorksheetSelectionMessage, applyAgentControlPatch, requiresWorksheetSelection, runAgentModeTurn, systemPrompt, t],
  );

  const datasetAttachment = useMemo<AiChatAttachment | undefined>(() => {
    if (!rawData) return undefined;
    return {
      name: rawData.fileName || t('ai.uploadedDataset'),
      type: rawData.fileType || undefined,
      rows: rawData.data.length,
      columns: rawData.headers.length,
    };
  }, [rawData, t]);

  const regenerateAssistantForUserIndex = useCallback(
    async (userIndex: number, assistantIndex: number) => {
      if (requestInFlightRef.current) {
        return;
      }

      requestInFlightRef.current = true;

      const { apiUrl, apiKey, model } = resolveAiRuntimeConfig();
      if (!apiUrl || !apiKey || !model) {
        setError(t('ai.notConfigured'));
        requestInFlightRef.current = false;
        return;
      }
      const trimmedUrl = apiUrl.replace(/\/$/, '');
      const endpoint = /\/v1\/chat\/completions$/i.test(trimmedUrl)
        ? trimmedUrl
        : `${trimmedUrl}/v1/chat/completions`;
      const agentEndpoint = /\/v1\/chat\/completions$/i.test(trimmedUrl)
        ? trimmedUrl.replace(/\/v1\/chat\/completions$/i, '/v1/agent/turn')
        : `${trimmedUrl}/v1/agent/turn`;
      const normalizedModel = model.trim().toLowerCase();
      const shouldSendTemperature = !normalizedModel.startsWith('gpt');

      const convo = conversationRef.current;
      const targetAssistant = convo[assistantIndex];
      if (!targetAssistant || targetAssistant.role !== 'assistant') return;

      setIsLoading(true);
      setError(null);
      const startTime = Date.now();

      try {
        // Build messages up to and including the parent user message
        const subset = convo.slice(0, userIndex + 1);
        if (targetAssistant.agentModeRequest) {
          const result = await runAgentModeTurn(subset, agentEndpoint, apiKey, model, shouldSendTemperature);
          applyAgentControlPatch(result.controlPatch);
          targetAssistant.content = result.content;
          targetAssistant.reasoning = result.reasoning ?? undefined;
          targetAssistant.tokenCount = tokenCountFor(result.content);
          targetAssistant.responseTimeMs = Math.max(0, Date.now() - startTime);
          setMessages([...conversationRef.current]);
          return;
        }

        const response = await fetch(endpoint, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${apiKey}`,
          },
          body: JSON.stringify({
            model,
            messages: [
              { role: 'system', content: systemPrompt },
              ...subset.map((m) => ({ role: m.role, content: m.content })),
            ],
            ...(shouldSendTemperature ? { temperature: 0.2 } : {}),
            stream: true,
          }),
        });

        const contentType = response.headers.get('content-type') || '';
        const supportsStream = response.ok && contentType.includes('text/event-stream');

        // Reset target content while regenerating
        targetAssistant.content = '';
        setMessages([...convo]);

        if (supportsStream && response.body) {
          const reader = response.body.getReader();
          const decoder = new TextDecoder('utf-8');
          let buffer = '';
          let doneStreaming = false;

          const applyDelta = (delta: string) => {
            if (!delta) return;
            targetAssistant.content += delta;
            setMessages([...conversationRef.current]);
          };

          const processEvent = (rawEvent: string) => {
            const lines = rawEvent.split('\n');
            for (const line of lines) {
              const trimmed = line.trim();
              if (!trimmed || trimmed.startsWith(':')) continue;
              if (!trimmed.startsWith('data:')) continue;
              const data = trimmed.slice(5).trim();
              if (data === '[DONE]') {
                doneStreaming = true;
                return;
              }
              try {
                const parsed = JSON.parse(data);
                const piece: string | undefined = parsed?.choices?.[0]?.delta?.content;
                if (typeof piece === 'string') {
                  applyDelta(piece);
                }
              } catch {
                // ignore
              }
            }
          };

          while (!doneStreaming) {
            const { done, value } = await reader.read();
            if (done) break;
            buffer += decoder.decode(value, { stream: true });
            let boundary = buffer.indexOf('\n\n');
            while (boundary !== -1) {
              const eventChunk = buffer.slice(0, boundary);
              buffer = buffer.slice(boundary + 2);
              processEvent(eventChunk);
              if (doneStreaming) break;
              boundary = buffer.indexOf('\n\n');
            }
          }

          if (buffer && !doneStreaming) {
            processEvent(buffer);
          }
          targetAssistant.tokenCount = tokenCountFor(targetAssistant.content);
          targetAssistant.responseTimeMs = Math.max(0, Date.now() - startTime);
          conversationRef.current = [...conversationRef.current];
          setMessages([...conversationRef.current]);
        } else {
          if (!response.ok) {
            throw new Error(await extractAiErrorMessage(response));
          }
          const payload = await response.json();
          const assistantText: string | undefined = payload?.choices?.[0]?.message?.content?.trim();
          if (!assistantText) {
            throw new Error('The AI service returned an empty response.');
          }
          targetAssistant.content = assistantText;
          targetAssistant.tokenCount = tokenCountFor(assistantText);
          targetAssistant.responseTimeMs = Math.max(0, Date.now() - (startTime));
          setMessages([...conversationRef.current]);
        }
      } catch (err) {
        const message = err instanceof Error ? err.message : 'Unexpected error while contacting the AI service.';
        setError(message);
      } finally {
        setIsLoading(false);
        requestInFlightRef.current = false;
      }
    },
    [applyAgentControlPatch, runAgentModeTurn, systemPrompt, t],
  );

  const handleRegenerate = (message: AiChatMessage) => {
    if (message.role !== 'assistant' || !message.parentUserId) return;
    const convo = conversationRef.current;
    const assistantIndex = convo.findIndex((m) => m.id === message.id);
    const userIndex = convo.findIndex((m) => m.id === message.parentUserId);
    if (assistantIndex === -1 || userIndex === -1) return;
    void regenerateAssistantForUserIndex(userIndex, assistantIndex);
  };

  const handleEditClick = (message: AiChatMessage) => {
    if (message.role !== 'user') return;
    setEditingId(message.id);
    setEditDraft(message.content);
  };

  const handleEditCancel = () => {
    setEditingId(null);
    setEditDraft('');
  };

  const handleEditSave = () => {
    if (!editingId) return;
    const trimmed = editDraft.trim();
    if (!trimmed) return;
    const convo = conversationRef.current;
    const userIndex = convo.findIndex((m) => m.id === editingId);
    if (userIndex === -1) return;

    // Update the user message content
    convo[userIndex] = {
      ...convo[userIndex],
      content: trimmed,
    };
    setMessages([...convo]);

    // Find the assistant reply tied to this user message
    const assistantIndex = convo.findIndex((m) => m.role === 'assistant' && m.parentUserId === editingId);
    if (assistantIndex !== -1) {
      void regenerateAssistantForUserIndex(userIndex, assistantIndex);
    }

    setEditingId(null);
    setEditDraft('');
  };

  useEffect(() => {
    const selectionContext = rawData?.sheets?.length
      ? `${rawData.fileName || 'dataset'}::${rawData.sheets.map((sheet) => sheet.name).join('|')}`
      : rawData?.fileName ?? null;

    if (sheetSelectionContextRef.current === selectionContext) {
      return;
    }

    sheetSelectionContextRef.current = selectionContext;

    if (rawData?.sheets && rawData.sheets.length > 1) {
      setSelectedAiSheetIndex(null);
      appendWorksheetSelectionMessage();
    } else {
      setSelectedAiSheetIndex(rawData ? (rawData.activeSheetIndex ?? 0) : null);
    }
  }, [appendWorksheetSelectionMessage, rawData]);

  useEffect(() => {
    if (!hasInitialized) {
      if (rawData && datasetSummary) {
        if (rawData.sheets && rawData.sheets.length > 1 && selectedAiSheetIndex === null) {
          const welcomeMessage: AiChatMessage = {
            id: 'assistant-welcome-multisheet',
            role: 'assistant',
            content: t('ai.welcomeMessage'),
            createdAt: Date.now(),
            autoGenerated: true,
          };

          const sheetMessage: AiChatMessage = {
            id: `assistant-sheets-initial-${Date.now()}`,
            role: 'assistant',
            content: t('ai.selectWorksheetPrompt'),
            createdAt: Date.now(),
            autoGenerated: true,
            worksheetOptions,
          };

          conversationRef.current = [welcomeMessage, sheetMessage];
          setMessages([welcomeMessage, sheetMessage]);
          setHasInitialized(true);
          return;
        }

        lastSummaryRef.current = datasetSummary;
        setHasInitialized(true);
        void sendMessage(buildInitialUserPrompt(datasetSummary, selectedChartType, friendlyChartName, language), {
          skipInputReset: true,
          autoGenerated: true,
          attachment: datasetAttachment,
        });
      } else {
        const welcomeMessage: AiChatMessage = {
          id: 'assistant-welcome',
          role: 'assistant',
          content:
            t('ai.welcomeMessage'),
          createdAt: Date.now(),
          autoGenerated: true,
        };
        conversationRef.current = [welcomeMessage];
        setMessages([welcomeMessage]);
        setHasInitialized(true);
      }
    }
  }, [datasetAttachment, datasetSummary, friendlyChartName, hasInitialized, rawData, selectedAiSheetIndex, selectedChartType, sendMessage, language, t, worksheetOptions]);

  useEffect(() => {
    if (!hasInitialized || !datasetSummary) {
      return;
    }

    if (agentModeEnabled) {
      return;
    }

    if (rawData?.sheets && rawData.sheets.length > 1 && selectedAiSheetIndex === null) {
      return;
    }

    if (lastSummaryRef.current === datasetSummary) {
      return;
    }

    lastSummaryRef.current = datasetSummary;
    void sendMessage(buildDatasetUpdatePrompt(datasetSummary, language), {
      skipInputReset: true,
      autoGenerated: true,
      attachment: datasetAttachment,
    });
  }, [agentModeEnabled, datasetAttachment, datasetSummary, hasInitialized, language, rawData?.sheets, selectedAiSheetIndex, sendMessage]);

  useEffect(() => {
    if (!hasInitialized) {
      return;
    }

    if (rawData) {
      return;
    }

    if (lastSummaryRef.current === null) {
      return;
    }

    lastSummaryRef.current = null;
    appendAssistantMessage(
      t('ai.datasetCleared'),
    );
  }, [appendAssistantMessage, hasInitialized, rawData, t]);

  useEffect(() => {
    if (!scrollContainerRef.current) {
      return;
    }
    scrollContainerRef.current.scrollTop = scrollContainerRef.current.scrollHeight;
  }, [messages]);

  useEffect(() => {
    if (!agentModeEnabled) {
      setAgentFeedback(null);
      agentAutopilotContextRef.current = null;
      suppressNextAgentAutopilotRef.current = false;
    }
  }, [agentModeEnabled]);

  useEffect(() => {
    if (!agentModeEnabled || !hasInitialized || !datasetSummary || requiresWorksheetSelection || isLoading) {
      return;
    }

    const contextSignature = `${selectedAiSheetIndex ?? -1}::${datasetSummary}`;

    if (suppressNextAgentAutopilotRef.current) {
      if (agentAutopilotContextRef.current !== contextSignature) {
        // Data has actually changed – consume the suppress flag and cache the new signature
        suppressNextAgentAutopilotRef.current = false;
        agentAutopilotContextRef.current = contextSignature;
      }
      return;
    }

    if (agentAutopilotContextRef.current === contextSignature) {
      return;
    }

    agentAutopilotContextRef.current = contextSignature;
    void sendMessage(buildAgentAutopilotPrompt(datasetSummary, selectedChartType, friendlyChartName, language), {
      skipInputReset: true,
      autoGenerated: true,
      hideUserMessage: true,
      attachment: datasetAttachment,
    });
  }, [
    agentModeEnabled,
    datasetAttachment,
    datasetSummary,
    friendlyChartName,
    hasInitialized,
    isLoading,
    language,
    requiresWorksheetSelection,
    selectedAiSheetIndex,
    selectedChartType,
    sendMessage,
  ]);

  const handleSubmit = (event: FormEvent) => {
    event.preventDefault();
    void sendMessage(inputValue);
  };

  const visibleMessages = useMemo(() => {
    const hiddenAutoUserIds = new Set<string>();

    return messages.filter((message) => {
      if (message.hidden) {
        return false;
      }

      if (agentModeEnabled && message.role === 'user' && message.autoGenerated && message.agentModeRequest) {
        hiddenAutoUserIds.add(message.id);
        return false;
      }

      if (
        agentModeEnabled
        && message.role === 'assistant'
        && message.parentUserId
        && hiddenAutoUserIds.has(message.parentUserId)
        && !message.agentModeRequest
      ) {
        return false;
      }

      return true;
    });
  }, [agentModeEnabled, messages]);

  return (
    <div className="mt-4 overflow-hidden rounded-2xl border border-teal-100 bg-white shadow-inner" dir={language === 'he' ? 'rtl' : 'ltr'}>
      <div className="flex items-start justify-between border-b border-teal-100 bg-teal-50/60 px-4 py-3">
        <div className="flex items-center gap-2 text-teal-700">
          <Sparkles className="h-5 w-5" aria-hidden="true" />
          <div>
            <p className="text-sm font-semibold">{t('ai.title')}</p>
            <p className="text-xs text-gray-600">{t('ai.subtitle')}</p>
          </div>
        </div>
        <button
          type="button"
          onClick={onClose}
          className="text-gray-400 transition hover:text-gray-600"
          aria-label={t('ai.close')}
        >
          <X className="h-4 w-4" aria-hidden="true" />
        </button>
      </div>

      {error && (
        <div className="border-b border-red-100 bg-red-50 px-4 py-2 text-xs text-red-700">
          {error}
        </div>
      )}

      {agentFeedback && (
        <div className="border-b border-teal-100 bg-teal-50 px-4 py-2 text-xs text-teal-700">
          {agentFeedback}
        </div>
      )}

      <div ref={scrollContainerRef} className="max-h-80 space-y-3 overflow-y-auto px-4 py-4 text-sm">
        {visibleMessages.map((message) => {
          const isAssistant = message.role === 'assistant';
          const hasAttachment = Boolean(message.attachment);
          const hasWorksheetOptions = Boolean(message.worksheetOptions?.length);
          const bubbleBase = isAssistant
            ? 'bg-teal-50 text-gray-700 ring-1 ring-inset ring-teal-100 rounded-bl-none'
            : 'bg-teal-600 text-white rounded-br-none';
          const bubblePadding = isAssistant
            ? 'px-3 py-2 pb-7'
            : hasAttachment
              ? 'p-3'
              : 'px-3 py-2 pb-7';
          const bubbleWhitespace = isAssistant ? 'whitespace-normal' : hasAttachment ? 'whitespace-normal' : 'whitespace-pre-wrap';
          const actionColor = isAssistant ? 'text-teal-700/70 hover:text-teal-700' : 'text-white/80 hover:text-white';
          const metricColor = isAssistant ? 'text-teal-700/60' : 'text-white/80';
          const attachmentMetaParts: string[] = [];
          if (message.attachment?.type) {
            attachmentMetaParts.push(message.attachment.type.toUpperCase());
          }
          if (message.attachment?.rows !== undefined && message.attachment?.columns !== undefined) {
            attachmentMetaParts.push(
              `${message.attachment.rows} ${t('fileUpload.rows')} • ${message.attachment.columns} ${t('fileUpload.columns')}`,
            );
          }
          const attachmentMeta = attachmentMetaParts.join(' · ');
          const showEdit = !isAssistant && !message.autoGenerated && !hasAttachment;
          const visibleAssistantContent = message.content;
          return (
            <div key={message.id} className={`flex ${isAssistant ? 'justify-start' : 'justify-end'}`}>
              <div className="relative group max-w-[90%]">
                <div
                  className={`relative rounded-2xl ${bubblePadding} shadow-sm ${bubbleBase} ${bubbleWhitespace}`}
                >
                  {isAssistant ? (
                    <>
                      {message.reasoning && (
                        <ChainOfThought className="mb-3">
                          <ChainOfThoughtHeader>{t('ai.thinking')}</ChainOfThoughtHeader>
                          <ChainOfThoughtContent>
                            <ChainOfThoughtStep label={t('ai.thinking')} status="complete">
                              <div className="text-xs whitespace-pre-wrap text-gray-600 dark:text-gray-400">
                                {message.reasoning}
                              </div>
                            </ChainOfThoughtStep>
                          </ChainOfThoughtContent>
                        </ChainOfThought>
                      )}
                      <MarkdownText text={visibleAssistantContent} />
                      {hasWorksheetOptions && (
                        <div className="mt-3 flex flex-wrap gap-2">
                          {message.worksheetOptions?.map((option) => (
                            <button
                              key={`${message.id}-${option.index}`}
                              type="button"
                              onClick={() => handleWorksheetSelect(option.index)}
                              className="rounded-full border border-teal-300 bg-white px-3 py-1 text-xs font-medium text-teal-700 transition hover:bg-teal-50"
                            >
                              {option.name} ({option.rows} {t('fileUpload.rows')}, {option.columns} {t('fileUpload.columns')})
                            </button>
                          ))}
                        </div>
                      )}
                    </>
                  ) : hasAttachment ? (
                    <div className="flex items-center gap-3 rounded-xl border border-white/30 bg-white/10 px-3 py-2">
                      <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-white/20 text-white">
                        <FileSpreadsheet className="h-5 w-5" aria-hidden="true" />
                      </div>
                      <div className="min-w-0">
                        <p className="text-sm font-semibold truncate">{message.attachment?.name}</p>
                        {attachmentMeta && (
                          <p className="text-xs text-white/80">{attachmentMeta}</p>
                        )}
                      </div>
                      <span className="sr-only">{message.content}</span>
                    </div>
                  ) : (
                    message.content
                  )}

                  {isAssistant ? (
                    <div className="pointer-events-none absolute inset-x-2 bottom-1 flex items-center justify-between opacity-0 group-hover:opacity-100 transition-opacity">
                      <div className="pointer-events-auto flex items-center gap-1">
                        <button
                          type="button"
                          className={`p-1 rounded-md transition-colors ${actionColor}`}
                          onClick={() => handleRegenerate(message)}
                          aria-label={t('ai.regenerate')}
                        >
                          <RefreshCcw size={14} />
                        </button>
                        <button
                          type="button"
                          className={`p-1 rounded-md transition-colors ${actionColor}`}
                          onClick={() => handleCopy(message.content)}
                          aria-label={t('ai.copy')}
                        >
                          <Copy size={14} />
                        </button>
                        <button
                          type="button"
                          className={`p-1 rounded-md transition-colors ${actionColor}`}
                          onClick={() => handleDownload(message.content)}
                          aria-label={t('ai.download')}
                        >
                          <Download size={14} />
                        </button>
                      </div>
                      <div className={`flex items-center gap-3 text-[11px] ${metricColor}`}>
                        <span className="flex items-center gap-1">
                          <Hash size={12} />
                          {message.tokenCount ?? '—'}
                        </span>
                        <span className="flex items-center gap-1">
                          <Clock size={12} />
                          {message.responseTimeMs !== undefined
                            ? `${(message.responseTimeMs / 1000).toFixed(2)}s`
                            : '—'}
                        </span>
                      </div>
                    </div>
                  ) : showEdit ? (
                    <div className="pointer-events-none absolute inset-x-2 bottom-1 flex items-center justify-end opacity-0 group-hover:opacity-100 transition-opacity">
                      <div className="pointer-events-auto">
                        <button
                          type="button"
                          className={`p-1 rounded-md transition-colors ${actionColor}`}
                          onClick={() => handleEditClick(message)}
                          aria-label={t('ai.edit')}
                        >
                          <Edit3 size={14} />
                        </button>
                      </div>
                    </div>
                  ) : null}
                </div>
              </div>
            </div>
          );
        })}

        {isLoading && (
          <div className="flex items-center gap-2 text-teal-600">
            <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />
            <span>{t('ai.thinking')}</span>
          </div>
        )}
      </div>

      {editingId && (
        <div className="border-t border-teal-100 bg-teal-50/40 px-4 py-3">
          <label htmlFor="edit-question" className="block text-xs font-medium text-slate-600 uppercase mb-2">
            {t('ai.editLabel')}
          </label>
          <textarea
            id="edit-question"
            className="w-full rounded-lg border border-slate-300 focus:border-teal-500 focus:ring-2 focus:ring-teal-100 px-3 py-2 text-sm text-slate-700"
            rows={3}
            value={editDraft}
            onChange={(e) => setEditDraft(e.target.value)}
          />
          <div className="mt-3 flex justify-end gap-2">
            <button
              type="button"
              className="inline-flex items-center gap-1 text-sm font-medium text-slate-600 hover:text-slate-800"
              onClick={handleEditCancel}
            >
              <X size={16} />
              {t('common.cancel')}
            </button>
            <button
              type="button"
              className="inline-flex items-center gap-1 text-sm font-medium text-teal-700 hover:text-teal-800 disabled:opacity-60"
              onClick={handleEditSave}
              disabled={editDraft.trim().length === 0}
            >
              <Check size={16} />
              {t('ai.saveChanges')}
            </button>
          </div>
        </div>
      )}

      <form onSubmit={handleSubmit} className="border-t border-teal-100 bg-white/80 px-4 py-3">
        <label className="sr-only" htmlFor="ai-message">
          {t('ai.title')}
        </label>
        <textarea
          id="ai-message"
          className="h-20 w-full resize-none rounded-xl border border-teal-100 bg-white px-3 py-2 text-sm text-gray-700 shadow-sm focus:border-teal-500 focus:outline-none focus:ring-2 focus:ring-teal-200"
          placeholder={t('ai.placeholder')}
          value={inputValue}
          onChange={(event) => setInputValue(event.target.value)}
          onKeyDown={(event) => {
            if (event.key === 'Enter' && !event.shiftKey && !editingId) {
              event.preventDefault();
              event.currentTarget.form?.requestSubmit();
            }
          }}
          disabled={isLoading || !!editingId}
        />
        <div className="mt-2 flex items-center justify-between">
          <button
            type="button"
            className={`rounded-full transition-colors duration-200 flex items-center gap-1.5 px-2 py-1 border h-8 ${agentModeEnabled ? 'bg-emerald-600 border-emerald-600 text-white' : 'bg-gray-100 border-gray-300 text-gray-400 hover:bg-gray-200 hover:text-gray-600'}`}
            onClick={() => {
              setAgentModeEnabled((prev) => !prev);
              setAgentFeedback(null);
            }}
            aria-pressed={agentModeEnabled}
            title={agentModeEnabled ? t('ai.agentModeOn') : 'Agent mode: Off'}
          >
            <Sparkles className="h-3.5 w-3.5 flex-shrink-0" aria-hidden="true" />
            <AnimatePresence initial={false}>
              {agentModeEnabled && (
                <motion.span
                  initial={{ width: 0, opacity: 0 }}
                  animate={{ width: 'auto', opacity: 1 }}
                  exit={{ width: 0, opacity: 0 }}
                  transition={{ duration: 0.15, ease: 'easeInOut' }}
                  className="text-[11px] font-medium overflow-hidden whitespace-nowrap flex-shrink-0"
                >
                  {t('ai.agentModeOn')}
                </motion.span>
              )}
            </AnimatePresence>
          </button>
          <button
            type="submit"
            className="inline-flex items-center gap-2 rounded-full bg-teal-600 px-4 py-2 text-sm font-medium text-white shadow-md transition hover:bg-teal-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-500 disabled:cursor-not-allowed disabled:opacity-60"
            disabled={isLoading || !!editingId || !inputValue.trim() || requiresWorksheetSelection}
          >
            {isLoading ? (
              <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />
            ) : (
              <Send className="h-4 w-4" aria-hidden="true" />
            )}
            <span>{isLoading ? t('ai.sending') : t('ai.send')}</span>
          </button>
        </div>
        <p className="mt-1 text-right text-[11px] text-teal-700/80">{t('ai.agentHint')}</p>
      </form>
    </div>
  );
};

export default AiAssistantPanel;
