import React, { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Loader2, Send, Sparkles, X, RefreshCcw, Hash, Clock, Copy, Download, Edit3, Check, FileSpreadsheet } from 'lucide-react';
import { useAppContext } from '../../context/AppContext';
import { useLanguage } from '../../context/LanguageContext';
import {
  buildAssistantSystemPrompt,
  buildDatasetUpdatePrompt,
  buildInitialUserPrompt,
  summarizeDatasetForAi,
} from '../../utils/aiHelpers';
import type { AiChatAttachment, AiChatMessage } from '../../types/AiTypes';
import { chartMeta } from '../../types/chartMeta';
import { MarkdownText } from '../common/MarkdownText';

interface AiAssistantPanelProps {
  onClose: () => void;
}

const AiAssistantPanel: React.FC<AiAssistantPanelProps> = ({ onClose }) => {
  const {
    rawData,
    processedData,
    selectedColumns,
    xAxisColumn,
    sampleSize,
    selectedChartType,
  } = useAppContext();
  
  const { language, t } = useLanguage();

  const [messages, setMessages] = useState<AiChatMessage[]>([]);
  const [inputValue, setInputValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [hasInitialized, setHasInitialized] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editDraft, setEditDraft] = useState('');
  const conversationRef = useRef<AiChatMessage[]>([]);
  const lastSummaryRef = useRef<string | null>(null);
  const scrollContainerRef = useRef<HTMLDivElement | null>(null);

  const systemPrompt = useMemo(() => buildAssistantSystemPrompt(language), [language]);
  const friendlyChartName = useMemo(
    () => chartMeta[selectedChartType]?.name ?? selectedChartType,
    [selectedChartType],
  );
  const datasetSummary = useMemo(
    () =>
      summarizeDatasetForAi(
        rawData,
        processedData,
        selectedColumns,
        xAxisColumn,
        sampleSize,
      ),
    [processedData, rawData, sampleSize, selectedColumns, xAxisColumn],
  );

  const appendAssistantMessage = useCallback((content: string) => {
    const assistantMessage: AiChatMessage = {
      id: `assistant-${Date.now()}`,
      role: 'assistant',
      content,
      createdAt: Date.now(),
      autoGenerated: true,
    };
    const updated = [...conversationRef.current, assistantMessage];
    conversationRef.current = updated;
    setMessages(updated);
    return assistantMessage;
  }, []);

  const tokenCountFor = (content: string) => {
    const wordCount = content.trim() ? content.trim().split(/\s+/).length : 0;
    return Math.max(1, Math.ceil(wordCount * 1.35));
  };

  const handleCopy = async (content: string) => {
    try {
      await navigator.clipboard.writeText(content);
    } catch {
      // noop
    }
  };

  const handleDownload = (content: string) => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'assistant-response.txt';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const sendMessage = useCallback(
    async (
      content: string,
      options?: {
        skipInputReset?: boolean;
        autoGenerated?: boolean;
        attachment?: AiChatAttachment;
      },
    ) => {
      const trimmed = content.trim();
      if (!trimmed) {
        return;
      }

      const userMessage: AiChatMessage = {
        id: `user-${Date.now()}`,
        role: 'user',
        content: trimmed,
        createdAt: Date.now(),
        autoGenerated: options?.autoGenerated,
        attachment: options?.attachment,
      };

      const conversationWithUser = [...conversationRef.current, userMessage];
      conversationRef.current = conversationWithUser;
      setMessages(conversationWithUser);
      if (!options?.skipInputReset) {
        setInputValue('');
      }

      setIsLoading(true);
      setError(null);

      const apiUrl = import.meta.env.VITE_AI_API_URL as string | undefined;
      const apiKey = import.meta.env.VITE_AI_API_KEY as string | undefined;
      const model = (import.meta.env.VITE_AI_MODEL as string | undefined) ?? 'gpt-4o-mini';

      if (!apiUrl || !apiKey) {
        setError(t('ai.notConfigured'));
        appendAssistantMessage(
          t('ai.configError'),
        );
        setIsLoading(false);
        return;
      }

      const trimmedUrl = apiUrl.replace(/\/$/, '');
      const endpoint = /\/v1\/chat\/completions$/i.test(trimmedUrl)
        ? trimmedUrl
        : `${trimmedUrl}/v1/chat/completions`;

      try {
        const startTime = Date.now();
        const response = await fetch(endpoint, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${apiKey}`,
          },
          body: JSON.stringify({
            model,
            messages: [
              { role: 'system', content: systemPrompt },
              ...conversationWithUser.map((message) => ({
                role: message.role,
                content: message.content,
              })),
            ],
            temperature: 0.2,
            stream: true,
          }),
        });

        // If the server does not support streaming, fall back to JSON body
        const contentType = response.headers.get('content-type') || '';
        const supportsStream = response.ok && contentType.includes('text/event-stream');

        if (supportsStream && response.body) {
          const assistantMessage: AiChatMessage = {
            id: `assistant-${Date.now()}`,
            role: 'assistant',
            content: '',
            createdAt: Date.now(),
            parentUserId: userMessage.id,
          };
          const withAssistant = [...conversationWithUser, assistantMessage];
          conversationRef.current = withAssistant;
          setMessages(withAssistant);

          const reader = response.body.getReader();
          const decoder = new TextDecoder('utf-8');
          let buffer = '';
          let doneStreaming = false;

          const applyDelta = (delta: string) => {
            if (!delta) return;
            assistantMessage.content += delta;
            // Trigger React update with the mutated message
            setMessages([...conversationRef.current]);
          };

          const processEvent = (rawEvent: string) => {
            const lines = rawEvent.split('\n');
            for (const line of lines) {
              const trimmed = line.trim();
              if (!trimmed || trimmed.startsWith(':')) continue; // comment/keep-alive
              if (!trimmed.startsWith('data:')) continue;
              const data = trimmed.slice(5).trim();
              if (data === '[DONE]') {
                doneStreaming = true;
                return;
              }
              try {
                const parsed = JSON.parse(data);
                // OpenAI Chat Completions delta shape
                const piece: string | undefined = parsed?.choices?.[0]?.delta?.content;
                if (typeof piece === 'string') {
                  applyDelta(piece);
                }
              } catch {
                // Non-JSON data line; ignore
              }
            }
          };

          // Read the stream
          while (!doneStreaming) {
            const { done, value } = await reader.read();
            if (done) break;
            buffer += decoder.decode(value, { stream: true });
            let boundary = buffer.indexOf('\n\n');
            while (boundary !== -1) {
              const eventChunk = buffer.slice(0, boundary);
              buffer = buffer.slice(boundary + 2);
              processEvent(eventChunk);
              if (doneStreaming) break;
              boundary = buffer.indexOf('\n\n');
            }
          }

          // If any remainder exists, attempt to process it
          if (buffer && !doneStreaming) {
            processEvent(buffer);
          }

          // Finalize conversation state
          assistantMessage.tokenCount = tokenCountFor(assistantMessage.content);
          assistantMessage.responseTimeMs = Math.max(0, Date.now() - startTime);
          conversationRef.current = [...conversationRef.current];
          setMessages([...conversationRef.current]);
        } else {
          const payload = await response.json();
          if (!response.ok) {
            const message = payload?.error?.message ?? response.statusText;
            throw new Error(message);
          }
          const assistantText: string | undefined = payload?.choices?.[0]?.message?.content?.trim();
          if (!assistantText) {
            throw new Error('The AI service returned an empty response.');
          }
          const assistantMessage: AiChatMessage = {
            id: `assistant-${Date.now()}`,
            role: 'assistant',
            content: assistantText,
            createdAt: Date.now(),
            tokenCount: tokenCountFor(assistantText),
            responseTimeMs: 0,
            parentUserId: userMessage.id,
          };
          assistantMessage.responseTimeMs = Math.max(0, Date.now() - startTime);
          const conversationWithAssistant = [...conversationWithUser, assistantMessage];
          conversationRef.current = conversationWithAssistant;
          setMessages(conversationWithAssistant);
        }
      } catch (err) {
        const message = err instanceof Error ? err.message : 'Unexpected error while contacting the AI service.';
        setError(message);
        appendAssistantMessage(`${t('ai.serviceError')}${message}`);
      } finally {
        setIsLoading(false);
      }
    },
    [appendAssistantMessage, systemPrompt, t],
  );

  const datasetAttachment = useMemo<AiChatAttachment | undefined>(() => {
    if (!rawData) return undefined;
    return {
      name: rawData.fileName || t('ai.uploadedDataset'),
      type: rawData.fileType || undefined,
      rows: rawData.data.length,
      columns: rawData.headers.length,
    };
  }, [rawData, t]);

  const regenerateAssistantForUserIndex = useCallback(
    async (userIndex: number, assistantIndex: number) => {
      const apiUrl = import.meta.env.VITE_AI_API_URL as string | undefined;
      const apiKey = import.meta.env.VITE_AI_API_KEY as string | undefined;
      const model = (import.meta.env.VITE_AI_MODEL as string | undefined) ?? 'gpt-4o-mini';
      if (!apiUrl || !apiKey) {
        setError('AI assistant is not configured. Please set VITE_AI_API_URL and VITE_AI_API_KEY.');
        return;
      }
      const trimmedUrl = apiUrl.replace(/\/$/, '');
      const endpoint = /\/v1\/chat\/completions$/i.test(trimmedUrl)
        ? trimmedUrl
        : `${trimmedUrl}/v1/chat/completions`;

      const convo = conversationRef.current;
      const targetAssistant = convo[assistantIndex];
      if (!targetAssistant || targetAssistant.role !== 'assistant') return;

      setIsLoading(true);
      setError(null);
      const startTime = Date.now();

      try {
        // Build messages up to and including the parent user message
        const subset = convo.slice(0, userIndex + 1);
        const response = await fetch(endpoint, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${apiKey}`,
          },
          body: JSON.stringify({
            model,
            messages: [
              { role: 'system', content: systemPrompt },
              ...subset.map((m) => ({ role: m.role, content: m.content })),
            ],
            temperature: 0.2,
            stream: true,
          }),
        });

        const contentType = response.headers.get('content-type') || '';
        const supportsStream = response.ok && contentType.includes('text/event-stream');

        // Reset target content while regenerating
        targetAssistant.content = '';
        setMessages([...convo]);

        if (supportsStream && response.body) {
          const reader = response.body.getReader();
          const decoder = new TextDecoder('utf-8');
          let buffer = '';
          let doneStreaming = false;

          const applyDelta = (delta: string) => {
            if (!delta) return;
            targetAssistant.content += delta;
            setMessages([...conversationRef.current]);
          };

          const processEvent = (rawEvent: string) => {
            const lines = rawEvent.split('\n');
            for (const line of lines) {
              const trimmed = line.trim();
              if (!trimmed || trimmed.startsWith(':')) continue;
              if (!trimmed.startsWith('data:')) continue;
              const data = trimmed.slice(5).trim();
              if (data === '[DONE]') {
                doneStreaming = true;
                return;
              }
              try {
                const parsed = JSON.parse(data);
                const piece: string | undefined = parsed?.choices?.[0]?.delta?.content;
                if (typeof piece === 'string') {
                  applyDelta(piece);
                }
              } catch {
                // ignore
              }
            }
          };

          while (!doneStreaming) {
            const { done, value } = await reader.read();
            if (done) break;
            buffer += decoder.decode(value, { stream: true });
            let boundary = buffer.indexOf('\n\n');
            while (boundary !== -1) {
              const eventChunk = buffer.slice(0, boundary);
              buffer = buffer.slice(boundary + 2);
              processEvent(eventChunk);
              if (doneStreaming) break;
              boundary = buffer.indexOf('\n\n');
            }
          }

          if (buffer && !doneStreaming) {
            processEvent(buffer);
          }
          targetAssistant.tokenCount = tokenCountFor(targetAssistant.content);
          targetAssistant.responseTimeMs = Math.max(0, Date.now() - startTime);
          conversationRef.current = [...conversationRef.current];
          setMessages([...conversationRef.current]);
        } else {
          const payload = await response.json();
          if (!response.ok) {
            const message = payload?.error?.message ?? response.statusText;
            throw new Error(message);
          }
          const assistantText: string | undefined = payload?.choices?.[0]?.message?.content?.trim();
          if (!assistantText) {
            throw new Error('The AI service returned an empty response.');
          }
          targetAssistant.content = assistantText;
          targetAssistant.tokenCount = tokenCountFor(assistantText);
          targetAssistant.responseTimeMs = Math.max(0, Date.now() - (startTime));
          setMessages([...conversationRef.current]);
        }
      } catch (err) {
        const message = err instanceof Error ? err.message : 'Unexpected error while contacting the AI service.';
        setError(message);
      } finally {
        setIsLoading(false);
      }
    },
    [systemPrompt],
  );

  const handleRegenerate = (message: AiChatMessage) => {
    if (message.role !== 'assistant' || !message.parentUserId) return;
    const convo = conversationRef.current;
    const assistantIndex = convo.findIndex((m) => m.id === message.id);
    const userIndex = convo.findIndex((m) => m.id === message.parentUserId);
    if (assistantIndex === -1 || userIndex === -1) return;
    void regenerateAssistantForUserIndex(userIndex, assistantIndex);
  };

  const handleEditClick = (message: AiChatMessage) => {
    if (message.role !== 'user') return;
    setEditingId(message.id);
    setEditDraft(message.content);
  };

  const handleEditCancel = () => {
    setEditingId(null);
    setEditDraft('');
  };

  const handleEditSave = () => {
    if (!editingId) return;
    const trimmed = editDraft.trim();
    if (!trimmed) return;
    const convo = conversationRef.current;
    const userIndex = convo.findIndex((m) => m.id === editingId);
    if (userIndex === -1) return;

    // Update the user message content
    convo[userIndex] = {
      ...convo[userIndex],
      content: trimmed,
    };
    setMessages([...convo]);

    // Find the assistant reply tied to this user message
    const assistantIndex = convo.findIndex((m) => m.role === 'assistant' && m.parentUserId === editingId);
    if (assistantIndex !== -1) {
      void regenerateAssistantForUserIndex(userIndex, assistantIndex);
    }

    setEditingId(null);
    setEditDraft('');
  };

  useEffect(() => {
    if (!hasInitialized) {
      if (rawData && datasetSummary) {
        lastSummaryRef.current = datasetSummary;
        setHasInitialized(true);
        void sendMessage(buildInitialUserPrompt(datasetSummary, selectedChartType, friendlyChartName, language), {
          skipInputReset: true,
          autoGenerated: true,
          attachment: datasetAttachment,
        });
      } else {
        const welcomeMessage: AiChatMessage = {
          id: 'assistant-welcome',
          role: 'assistant',
          content:
            t('ai.welcomeMessage'),
          createdAt: Date.now(),
          autoGenerated: true,
        };
        conversationRef.current = [welcomeMessage];
        setMessages([welcomeMessage]);
        setHasInitialized(true);
      }
    }
  }, [datasetAttachment, datasetSummary, friendlyChartName, hasInitialized, rawData, selectedChartType, sendMessage, language, t]);

  useEffect(() => {
    if (!hasInitialized || !datasetSummary) {
      return;
    }

    if (lastSummaryRef.current === datasetSummary) {
      return;
    }

    lastSummaryRef.current = datasetSummary;
    void sendMessage(buildDatasetUpdatePrompt(datasetSummary, language), {
      skipInputReset: true,
      autoGenerated: true,
      attachment: datasetAttachment,
    });
  }, [datasetAttachment, datasetSummary, hasInitialized, sendMessage, language]);

  useEffect(() => {
    if (!hasInitialized) {
      return;
    }

    if (rawData) {
      return;
    }

    if (lastSummaryRef.current === null) {
      return;
    }

    lastSummaryRef.current = null;
    appendAssistantMessage(
      t('ai.datasetCleared'),
    );
  }, [appendAssistantMessage, hasInitialized, rawData, t]);

  useEffect(() => {
    if (!scrollContainerRef.current) {
      return;
    }
    scrollContainerRef.current.scrollTop = scrollContainerRef.current.scrollHeight;
  }, [messages]);

  const handleSubmit = (event: FormEvent) => {
    event.preventDefault();
    void sendMessage(inputValue);
  };

  return (
    <div className="mt-4 overflow-hidden rounded-2xl border border-teal-100 bg-white shadow-inner" dir={language === 'he' ? 'rtl' : 'ltr'}>
      <div className="flex items-start justify-between border-b border-teal-100 bg-teal-50/60 px-4 py-3">
        <div className="flex items-center gap-2 text-teal-700">
          <Sparkles className="h-5 w-5" aria-hidden="true" />
          <div>
            <p className="text-sm font-semibold">{t('ai.title')}</p>
            <p className="text-xs text-gray-600">{t('ai.subtitle')}</p>
          </div>
        </div>
        <button
          type="button"
          onClick={onClose}
          className="text-gray-400 transition hover:text-gray-600"
          aria-label={t('ai.close')}
        >
          <X className="h-4 w-4" aria-hidden="true" />
        </button>
      </div>

      {error && (
        <div className="border-b border-red-100 bg-red-50 px-4 py-2 text-xs text-red-700">
          {error}
        </div>
      )}

      <div ref={scrollContainerRef} className="max-h-80 space-y-3 overflow-y-auto px-4 py-4 text-sm">
        {messages.map((message) => {
          const isAssistant = message.role === 'assistant';
          const hasAttachment = Boolean(message.attachment);
          const bubbleBase = isAssistant
            ? 'bg-teal-50 text-gray-700 ring-1 ring-inset ring-teal-100 rounded-bl-none'
            : 'bg-teal-600 text-white rounded-br-none';
          const bubblePadding = isAssistant
            ? 'px-3 py-2 pb-7'
            : hasAttachment
              ? 'p-3'
              : 'px-3 py-2 pb-7';
          const bubbleWhitespace = isAssistant ? 'whitespace-normal' : hasAttachment ? 'whitespace-normal' : 'whitespace-pre-wrap';
          const actionColor = isAssistant ? 'text-teal-700/70 hover:text-teal-700' : 'text-white/80 hover:text-white';
          const metricColor = isAssistant ? 'text-teal-700/60' : 'text-white/80';
          const attachmentMetaParts: string[] = [];
          if (message.attachment?.type) {
            attachmentMetaParts.push(message.attachment.type.toUpperCase());
          }
          if (message.attachment?.rows !== undefined && message.attachment?.columns !== undefined) {
            attachmentMetaParts.push(
              `${message.attachment.rows} ${t('fileUpload.rows')} • ${message.attachment.columns} ${t('fileUpload.columns')}`,
            );
          }
          const attachmentMeta = attachmentMetaParts.join(' · ');
          const showEdit = !isAssistant && !message.autoGenerated && !hasAttachment;
          return (
            <div key={message.id} className={`flex ${isAssistant ? 'justify-start' : 'justify-end'}`}>
              <div className="relative group max-w-[90%]">
                <div
                  className={`relative rounded-2xl ${bubblePadding} shadow-sm ${bubbleBase} ${bubbleWhitespace}`}
                >
                  {isAssistant ? (
                    <MarkdownText text={message.content} />
                  ) : hasAttachment ? (
                    <div className="flex items-center gap-3 rounded-xl border border-white/30 bg-white/10 px-3 py-2">
                      <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-white/20 text-white">
                        <FileSpreadsheet className="h-5 w-5" aria-hidden="true" />
                      </div>
                      <div className="min-w-0">
                        <p className="text-sm font-semibold truncate">{message.attachment?.name}</p>
                        {attachmentMeta && (
                          <p className="text-xs text-white/80">{attachmentMeta}</p>
                        )}
                      </div>
                      <span className="sr-only">{message.content}</span>
                    </div>
                  ) : (
                    message.content
                  )}

                  {isAssistant ? (
                    <div className="pointer-events-none absolute inset-x-2 bottom-1 flex items-center justify-between opacity-0 group-hover:opacity-100 transition-opacity">
                      <div className="pointer-events-auto flex items-center gap-1">
                        <button
                          type="button"
                          className={`p-1 rounded-md transition-colors ${actionColor}`}
                          onClick={() => handleRegenerate(message)}
                          aria-label={t('ai.regenerate')}
                        >
                          <RefreshCcw size={14} />
                        </button>
                        <button
                          type="button"
                          className={`p-1 rounded-md transition-colors ${actionColor}`}
                          onClick={() => handleCopy(message.content)}
                          aria-label={t('ai.copy')}
                        >
                          <Copy size={14} />
                        </button>
                        <button
                          type="button"
                          className={`p-1 rounded-md transition-colors ${actionColor}`}
                          onClick={() => handleDownload(message.content)}
                          aria-label={t('ai.download')}
                        >
                          <Download size={14} />
                        </button>
                      </div>
                      <div className={`flex items-center gap-3 text-[11px] ${metricColor}`}>
                        <span className="flex items-center gap-1">
                          <Hash size={12} />
                          {message.tokenCount ?? '—'}
                        </span>
                        <span className="flex items-center gap-1">
                          <Clock size={12} />
                          {message.responseTimeMs !== undefined
                            ? `${(message.responseTimeMs / 1000).toFixed(2)}s`
                            : '—'}
                        </span>
                      </div>
                    </div>
                  ) : showEdit ? (
                    <div className="pointer-events-none absolute inset-x-2 bottom-1 flex items-center justify-end opacity-0 group-hover:opacity-100 transition-opacity">
                      <div className="pointer-events-auto">
                        <button
                          type="button"
                          className={`p-1 rounded-md transition-colors ${actionColor}`}
                          onClick={() => handleEditClick(message)}
                          aria-label={t('ai.edit')}
                        >
                          <Edit3 size={14} />
                        </button>
                      </div>
                    </div>
                  ) : null}
                </div>
              </div>
            </div>
          );
        })}

        {isLoading && (
          <div className="flex items-center gap-2 text-teal-600">
            <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />
            <span>{t('ai.thinking')}</span>
          </div>
        )}
      </div>

      {editingId && (
        <div className="border-t border-teal-100 bg-teal-50/40 px-4 py-3">
          <label htmlFor="edit-question" className="block text-xs font-medium text-slate-600 uppercase mb-2">
            {t('ai.editLabel')}
          </label>
          <textarea
            id="edit-question"
            className="w-full rounded-lg border border-slate-300 focus:border-teal-500 focus:ring-2 focus:ring-teal-100 px-3 py-2 text-sm text-slate-700"
            rows={3}
            value={editDraft}
            onChange={(e) => setEditDraft(e.target.value)}
          />
          <div className="mt-3 flex justify-end gap-2">
            <button
              type="button"
              className="inline-flex items-center gap-1 text-sm font-medium text-slate-600 hover:text-slate-800"
              onClick={handleEditCancel}
            >
              <X size={16} />
              {t('common.cancel')}
            </button>
            <button
              type="button"
              className="inline-flex items-center gap-1 text-sm font-medium text-teal-700 hover:text-teal-800 disabled:opacity-60"
              onClick={handleEditSave}
              disabled={editDraft.trim().length === 0}
            >
              <Check size={16} />
              {t('ai.saveChanges')}
            </button>
          </div>
        </div>
      )}

      <form onSubmit={handleSubmit} className="border-t border-teal-100 bg-white/80 px-4 py-3">
        <label className="sr-only" htmlFor="ai-message">
          {t('ai.title')}
        </label>
        <textarea
          id="ai-message"
          className="h-20 w-full resize-none rounded-xl border border-teal-100 bg-white px-3 py-2 text-sm text-gray-700 shadow-sm focus:border-teal-500 focus:outline-none focus:ring-2 focus:ring-teal-200"
          placeholder={t('ai.placeholder')}
          value={inputValue}
          onChange={(event) => setInputValue(event.target.value)}
          onKeyDown={(event) => {
            if (event.key === 'Enter' && !event.shiftKey && !editingId) {
              event.preventDefault();
              void sendMessage(inputValue);
            }
          }}
          disabled={isLoading || !!editingId}
        />
        <div className="mt-2 flex justify-end">
          <button
            type="submit"
            className="inline-flex items-center gap-2 rounded-full bg-teal-600 px-4 py-2 text-sm font-medium text-white shadow-md transition hover:bg-teal-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-teal-500 disabled:cursor-not-allowed disabled:opacity-60"
            disabled={isLoading || !!editingId || !inputValue.trim()}
          >
            {isLoading ? (
              <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />
            ) : (
              <Send className="h-4 w-4" aria-hidden="true" />
            )}
            <span>{isLoading ? t('ai.sending') : t('ai.send')}</span>
          </button>
        </div>
      </form>
    </div>
  );
};

export default AiAssistantPanel;
